spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: letsgoal
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver

server:
  servlet:
    context-path: /api/letsgoal
